apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/GiganticMinecraft/seichi-gateway-operator/config/default?ref=5281f03968e7f429b0a65477c9a739773d952f05

images:
  - name: controller
    newName: ghcr.io/giganticminecraft/seichi-gateway-operator
    newTag: sha-5281f03@sha256:2d356bc6db9e11efa83b902d9a57c4c73628b47475d61ee545e844bc01d6ed0f
