apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  namespace: seichi-minecraft
  name: bugsink-secret-credentials
spec:
  forceRegenerate: false
  fields:
    - fieldName: "secret_key"
      encoding: "hex"
      length: "50"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bugsink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugsink
  template:
    metadata:
      labels:
        app: bugsink
    spec:
      containers:
        - name: bugsink
          image: bugsink/bugsink:2.1.1
          ports:
            - containerPort: 9000
              protocol: TCP
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bugsink-secret-credentials
                  key: secret_key
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bugsink-db-credentials
                  key: password
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bugsink-admin-password
                  key: ADMIN_PASSWORD
            - name: CREATE_SUPERUSER
              value: "admin:$(ADMIN_PASSWORD)"
            - name: PORT
              value: "9000"
            - name: DATABASE_URL
              value: mysql://bugsink:$(MYSQL_PASSWORD)@mariadb/bugsink
            - name: SINGLE_TEAM
              value: "True"
            - name: SINGLE_USER
              value: "True"
            - name: USER_REGISTRATION
              value: "CB_NOBODY"
            - name: PHONEHOME
              value: "False"
            - name: USE_X_REAL_IP
              value: "True"
            - name: BEHIND_HTTPS_PROXY
              value: "True"
            - name: BASE_URL
              value: "https://bugsink-dsn.onp-k8s.admin.seichi.click"
            - name: ALLOWED_HOSTS
              value: "bugsink.onp-k8s.admin.seichi.click,bugsink-dsn.onp-k8s.admin.seichi.click,bugsink.seichi-minecraft"
            # https://github.com/bugsink/bugsink/blob/bddc2e8f640e82b7d1f861f1b8b363535d8a22a1/bugsink/conf_templates/singleserver.py.template#L41
            - name: TIME_ZONE
              value: "Asia/Tokyo"
          startupProbe:
            httpGet:
              path: /
              port: 9000
              httpHeaders:
                - name: Host
                  value: bugsink.seichi-minecraft
            failureThreshold: 60
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 9000
              httpHeaders:
                - name: Host
                  value: bugsink.seichi-minecraft
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 9000
              httpHeaders:
                - name: Host
                  value: bugsink.seichi-minecraft
            periodSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
              ephemeral-storage: 500Mi
            requests:
              cpu: 50m
              memory: 500Mi
              ephemeral-storage: 500Mi
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
