apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: seichi-minecraft
  labels:
    app: seichi-game-data-server
  name: seichi-game-data-server
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: seichi-game-data-server
  template:
    metadata:
      labels:
        app: seichi-game-data-server
    spec:
      containers:
        - resources:
            requests:
              memory: 128Mi

          envFrom:
            - configMapRef:
                name: seichi-game-data-server-config

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: mcserver-password

          image: ghcr.io/giganticminecraft/seichi-game-data-server:sha-019129d
          name: seichi-game-data-server
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            tcpSocket:
              port: 80
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          startupProbe:
            tcpSocket:
              port: 80
            # 最大30秒待つ
            failureThreshold: 6
            periodSeconds: 5
