apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: opencost
    repoURL: https://opencost.github.io/opencost-helm-chart
    targetRevision: 2.5.14
    helm:
      releaseName: opencost
      values: |
        opencost:
          prometheus:
            internal:
              serviceName: prometheus-kube-prometheus-prometheus
              namespaceName: monitoring
              port: 9090
          ui:
            enabled: true
          metrics:
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: opencost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
