apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: seichi-game-data-server
  namespace: argocd
spec:
  namespace: argocd
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: "seichi-minecraft-seichi-game-data-server"
      images:
        - alias: server
          imageName: ghcr.io/giganticminecraft/seichi-game-data-server
          commonUpdateSettings:
            updateStrategy: latest
            allowTags: "regexp:^sha-"
