apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: cluster-wide-apps
  source:
    repoURL: https://github.com/GiganticMinecraft/seichi_infra
    targetRevision: main
    path: seichi-onp-k8s/manifests/seichi-kubernetes/apps/thanos
    directory:
      # vendor 配下や jsonnetfile.json を ArgoCD の manifest scanner に拾わせない
      include: 'main.jsonnet'
      jsonnet:
        libs:
          - seichi-onp-k8s/manifests/seichi-kubernetes/apps/thanos/vendor
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
