# ref: https://docs.cilium.io/en/v1.18/network/bgp-control-plane/
#
# 各ノードのlocalASNを個別に設定する。
# CiliumBGPClusterConfigのデフォルト値(65301)をノードごとに上書き。
apiVersion: cilium.io/v2
kind: CiliumBGPNodeConfigOverride
metadata:
  name: override--seichi-onp-k8s-cp-1
spec:
  nodeRef: seichi-onp-k8s-cp-1
  bgpInstances:
    - name: router-peer
      localASN: 65201
---
apiVersion: cilium.io/v2
kind: CiliumBGPNodeConfigOverride
metadata:
  name: override--seichi-onp-k8s-cp-2
spec:
  nodeRef: seichi-onp-k8s-cp-2
  bgpInstances:
    - name: router-peer
      localASN: 65202
---
apiVersion: cilium.io/v2
kind: CiliumBGPNodeConfigOverride
metadata:
  name: override--seichi-onp-k8s-cp-3
spec:
  nodeRef: seichi-onp-k8s-cp-3
  bgpInstances:
    - name: router-peer
      localASN: 65203
---
apiVersion: cilium.io/v2
kind: CiliumBGPNodeConfigOverride
metadata:
  name: override--seichi-onp-k8s-wk-1
spec:
  nodeRef: seichi-onp-k8s-wk-1
  bgpInstances:
    - name: router-peer
      localASN: 65301
---
apiVersion: cilium.io/v2
kind: CiliumBGPNodeConfigOverride
metadata:
  name: override--seichi-onp-k8s-wk-2
spec:
  nodeRef: seichi-onp-k8s-wk-2
  bgpInstances:
    - name: router-peer
      localASN: 65302
---
apiVersion: cilium.io/v2
kind: CiliumBGPNodeConfigOverride
metadata:
  name: override--seichi-onp-k8s-wk-3
spec:
  nodeRef: seichi-onp-k8s-wk-3
  bgpInstances:
    - name: router-peer
      localASN: 65303
