# ref: https://docs.cilium.io/en/v1.18/network/bgp-control-plane/
#
# ノードごとのASNはCiliumBGPNodeConfigOverrideで上書きする。
# ここでは代表値としてwk-1のASNを指定している。
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-cluster-config
spec:
  nodeSelector:
    matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
          - seichi-onp-k8s-cp-1
          - seichi-onp-k8s-cp-2
          - seichi-onp-k8s-cp-3
          - seichi-onp-k8s-wk-1
          - seichi-onp-k8s-wk-2
          - seichi-onp-k8s-wk-3
  bgpInstances:
    - name: router-peer
      localASN: 65301
      peers:
        - name: router
          peerAddress: "192.168.3.254"
          peerASN: 65184
          peerConfigRef:
            name: peer-config--router
