apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seichi-portal-debezium-data
  namespace: seichi-minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
