name: K8s resource API version check with Pluto

on:
  pull_request:
    paths:
      - ".github/workflows/pluto.yaml"
      - "seichi-onp-k8s/manifests/seichi-kubernetes/**"

jobs:
  api-check:
    name: K8s resource API version check with Pluto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Download Pluto
        uses: FairwindsOps/pluto/github-action@5f85d3f5474aede69f17f71d3e0a36674b8b8b62 # master

      - name: Use pluto
        run: |
          pluto detect-files -d seichi-onp-k8s/manifests/seichi-kubernetes/apps --target-versions k8s=v1.34.2

      - name: Use pluto
        run: |
          pluto detect-files -d seichi-onp-k8s/manifests/seichi-kubernetes/app-templates --target-versions k8s=v1.34.2
