name: shellcheck

on:
  pull_request:
    paths:
      - "**.sh"
      - ".github/workflows/shellcheck.yaml"

jobs:
  shellcheck:
    name: shellcheck with reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: shellcheck
        uses: reviewdog/action-shellcheck@d0b8d5fd7fad6afdb6e1b6ce1778892be4d1f427 # v1.34.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          pattern: "*.sh"
