name: shellcheck

on:
  pull_request:
    paths:
      - "**.sh"
      - ".github/workflows/shellcheck.yaml"

jobs:
  shellcheck:
    name: shellcheck with reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: shellcheck
        uses: reviewdog/action-shellcheck@0a90156c6e0553996a217f0a9e09be6b0f6bee4c # v1.34.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          pattern: "*.sh"
