name: Validate Renovate config
on:
  pull_request:
    branches:
      - main
    paths:
      - renovate.json5
      - .github/workflows/validate-renovate-config.yaml
  push:
    branches:
      - main
    paths:
      - renovate.json5
      - .github/workflows/validate-renovate-config.yaml
jobs:
  validate:
    name: Validate Renovate config
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@1e1604219a6b38ae9a10aff42a28a3656322c31a # v2.4.1
