name: Validate Renovate config
on:
  pull_request:
    branches:
      - main
    paths:
      - renovate.json5
      - .github/workflows/validate-renovate-config.yaml
  push:
    branches:
      - main
    paths:
      - renovate.json5
      - .github/workflows/validate-renovate-config.yaml
jobs:
  validate:
    name: Validate Renovate config
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@394f7a3d2641cad2995938f9dc7e54580c8a7089 # v2.3.0
